/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classpriv;

import java.awt.ComponentOrientation;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author amnassar
 */

public class accountReport extends javax.swing.JFrame {
  Connection con ;  
     public  String LL=null;
    PreparedStatement pst ;
    Home h ;
    ResultSet rs;
     public Double total ;
   public  String from,to;
    
    public accountReport() {
        initComponents();
        con=DBConnect.connect();
 Calendar cal = new GregorianCalendar();
 int dayy = cal.get(Calendar.DAY_OF_MONTH);
                int monthh=cal.get(Calendar.MONTH)+1;
                int yearr = cal.get(Calendar.YEAR);
                  day.setText(Integer.toString(dayy));
                    month.setText(Integer.toString(monthh));
                year.setText(Integer.toString(yearr));
                day2.setText(Integer.toString(dayy));
                    month2.setText(Integer.toString(monthh));
                year2.setText(Integer.toString(yearr));
            

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancle = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        day2 = new javax.swing.JTextField();
        s5 = new javax.swing.JLabel();
        month2 = new javax.swing.JTextField();
        s6 = new javax.swing.JLabel();
        year2 = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        day = new javax.swing.JTextField();
        s3 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        s4 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();

        setUndecorated(true);

        jPanel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancle.setBackground(new java.awt.Color(98, 113, 146));
        cancle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        cancle.setForeground(new java.awt.Color(255, 255, 255));
        cancle.setText("اغلاق");
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });
        jPanel1.add(cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 80, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("الي");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 50, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("من");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 50, -1));

        day2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(day2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 60, 30));

        s5.setBackground(new java.awt.Color(255, 255, 255));
        s5.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.setText("/");
        jPanel1.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 10, -1));

        month2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(month2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 60, 30));

        s6.setBackground(new java.awt.Color(255, 255, 255));
        s6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s6.setForeground(new java.awt.Color(255, 255, 255));
        s6.setText("/");
        jPanel1.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 10, -1));

        year2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 60, 30));

        save.setBackground(new java.awt.Color(98, 113, 146));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("تقرير");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 120, 40));

        day.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, 30));

        s3.setBackground(new java.awt.Color(255, 255, 255));
        s3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setText("/");
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 10, -1));

        month.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 60, 30));

        s4.setBackground(new java.awt.Color(255, 255, 255));
        s4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setText("/");
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 10, -1));

        year.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/64586a0ad51dc03.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jLabel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 260));

        s1.setBackground(new java.awt.Color(255, 255, 255));
        s1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("/");
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 10, -1));

        s2.setBackground(new java.awt.Color(255, 255, 255));
        s2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setText("/");
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 10, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(458, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
       
        this.dispose();
    }//GEN-LAST:event_cancleActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

     from=year.getText()+"-"+month.getText()+"-"+day.getText();
     to=year2.getText()+"-"+month2.getText()+"-"+day2.getText();
     getTotal();
     InputStream in=null;
      try {
          
          
          String reportpath= "D:\\meal\\MrHossamReport\\AccountMonthely.jasper";
    Map<String,Object> para = new HashMap<String,Object>();
            para.put("total", total);
            para.put("from",from );
            para.put("to",to );
           

            JasperPrint j = JasperFillManager.fillReport(reportpath, para,con);
            JasperViewer.viewReport(j,false);
      }
     catch (JRException ex) {
            Logger.getLogger(reportr.class.getName()).log(Level.SEVERE, null, "بم يسجل غياب اي طالب اليوم");
        } finally {
        } 


         
        
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancle;
    public javax.swing.JTextField day;
    public javax.swing.JTextField day2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField month;
    public javax.swing.JTextField month2;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JButton save;
    public javax.swing.JTextField year;
    public javax.swing.JTextField year2;
    // End of variables declaration//GEN-END:variables


  private void getTotal() {
        from=year.getText()+"-"+month.getText()+"-"+day.getText();
     to=year2.getText()+"-"+month2.getText()+"-"+day2.getText();
        try {
             String sql="select sum(deduction.amount) as 'hello' from mrahmed.deduction where date between '"+from+"' and '"+to+"'";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
               String totall = rs.getString("hello");
               total=new Double(totall);
             }

         } catch (SQLException ex) {
             
         }
    }
}
