/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classpriv;

import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author amnassar
 */
public final class searchstudent extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
       Connection con ;
    PreparedStatement pst ;
    ResultSet rs;
     public String y ;
    
   
    public searchstudent() {
        initComponents();
        con=DBConnect.connect();
        privatetablelord();
        clear();
            TableCellRenderer rendererFromHeader = tdetails1.getTableHeader().getDefaultRenderer();
JLabel headerLabel = (JLabel) rendererFromHeader;
headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
      
          
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tdetails1 = new javax.swing.JTable();
        delete1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        cmgroup1 = new javax.swing.JComboBox();
        save1 = new javax.swing.JButton();
        phone1 = new javax.swing.JTextField();
        save3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        serial1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        serialid1 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdetails1.setBackground(new java.awt.Color(17, 39, 37));
        tdetails1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tdetails1.setForeground(new java.awt.Color(255, 255, 255));
        tdetails1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "المذكرات", "المجموعه", "رقم ولي الامر", "رقم الهاتف", "اسم الطالب", "الرقم التسلسلي"
            }
        ));
        tdetails1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails1.setRowHeight(25);
        tdetails1.setRowMargin(2);
        tdetails1.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tdetails1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetails1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tdetails1);
        if (tdetails1.getColumnModel().getColumnCount() > 0) {
            tdetails1.getColumnModel().getColumn(1).setMinWidth(400);
            tdetails1.getColumnModel().getColumn(1).setPreferredWidth(400);
            tdetails1.getColumnModel().getColumn(1).setMaxWidth(400);
            tdetails1.getColumnModel().getColumn(5).setMinWidth(100);
            tdetails1.getColumnModel().getColumn(5).setPreferredWidth(100);
            tdetails1.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 920, 280));

        delete1.setBackground(new java.awt.Color(98, 113, 146));
        delete1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setText("مسح");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 180, 50));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("المجموعه");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 160, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("الاسم");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 160, -1));

        name1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 230, 30));

        cmgroup1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "الثالث الثانوي" }));
        cmgroup1.setEnabled(false);
        jPanel1.add(cmgroup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 230, 30));

        save1.setBackground(new java.awt.Color(98, 113, 146));
        save1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save1.setForeground(new java.awt.Color(255, 255, 255));
        save1.setText("بحث");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel1.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, 40));

        phone1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 230, 30));

        save3.setBackground(new java.awt.Color(98, 113, 146));
        save3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save3.setForeground(new java.awt.Color(255, 255, 255));
        save3.setText("تفريغ");
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });
        jPanel1.add(save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 130, 40));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("الرقم التسلسلي");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 160, -1));

        serial1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(serial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 230, 30));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("رقم التليفون");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 160, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/myback.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        serialid1.setForeground(new java.awt.Color(255, 255, 255));
        serialid1.setText("Seriallllllllll");
        jPanel1.add(serialid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 190, 50));

        jTabbedPane1.addTab("مميز", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdetails1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetails1MouseClicked
  DefaultTableModel tmodel =(DefaultTableModel)tdetails1.getModel();
        //bid,name, price, publisher, book_type, b_code, date, category
        int selectrowindex=tdetails1.getSelectedRow();
       name1.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        phone1.setText(tmodel.getValueAt(selectrowindex, 3).toString());
         serial1.setText(tmodel.getValueAt(selectrowindex, 5).toString());
        cmgroup1.setSelectedItem(tmodel.getValueAt(selectrowindex, 1).toString());
        
                 
    }//GEN-LAST:event_tdetails1MouseClicked

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
         if(serialid1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "من فضلك اختر الطالب المراد ازالته ");

        }
        else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
            if(dialogResult == 0) {
                try {
                    String sql = "DELETE FROM mrahmed.privatestudents WHERE serial='"+serialid1.getText()+"'";
                    pst=(PreparedStatement) con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(rootPane, " تم ازاله الطالب بنجاح");
                    privatetablelord();
                } catch (SQLException ex) {

                }
                clear();
            }
            else
            {

                JOptionPane.showMessageDialog(this, " تم الغاء العمليه");
            }
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed

        
        String seriall= serial1.getText();
        String namee=name1.getText();
        String phonee=phone1.getText();
        String group = cmgroup1.getSelectedItem().toString();
       

            try {
                String sqll = "SELECT paper,serial,name,class,phone,pphone,groupp FROM mrahmed.privatestudents WHERE  1=1 ";
                if(!serial1.getText().trim().isEmpty())
                {
                    sqll=sqll+" AND serial ='"+seriall+"'";
                }
                else if (!name1.getText().trim().isEmpty())
                {
                    sqll=sqll+" AND name LIKE '%"+namee+"%'";
                }
            
                 else if (!phone1.getText().trim().isEmpty())
                {
                    sqll=sqll+" AND phone Like '%"+phonee+"%'";
                }
                else if ( !cmgroup1.getSelectedItem().toString().trim().isEmpty() || cmgroup1.getSelectedIndex()!=0)
                {
                    sqll=sqll+" AND groupp='"+group+"'";
                }
                pst=(PreparedStatement) con.prepareStatement(sqll);
                rs=pst.executeQuery();
                DefaultTableModel model =(DefaultTableModel)tdetails1.getModel();
                model.setRowCount(0);
int k = 0 ;
                while (rs.next())
                {
                    Object row[] = {
                  
                           rs.getString("paper"),
                      rs.getString("groupp"),
                         rs.getString("pphone"),
                       rs.getString("phone"),
                       rs.getString("class"),
                        rs.getString("name"),
                        rs.getString("serial"),
                        
                    };
                    model.addRow(row);
k++;
                }
                 for(int i = k ;i<11;i++)
                {
                 Object rowData[] = {
                       "",
                     "",
                     "",
                     "",
                     "",
                       };
                model.addRow(rowData);
                } 
            }
            catch (SQLException ex) {
            }
            

    }//GEN-LAST:event_save1ActionPerformed

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed
        clear();
    }//GEN-LAST:event_save3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmgroup1;
    private javax.swing.JButton delete1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField phone1;
    private javax.swing.JButton save1;
    private javax.swing.JButton save3;
    private javax.swing.JTextField serial1;
    private javax.swing.JLabel serialid1;
    private javax.swing.JTable tdetails1;
    // End of variables declaration//GEN-END:variables
 public void privatetablelord()
    {
        try {
            String sqll = "SELECT paper,serial,name,class,phone,pphone,groupp FROM mrahmed.privatestudents";
              pst=(PreparedStatement) con.prepareStatement(sqll);
            rs=pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel)tdetails1.getModel(); 
                model.setRowCount(0);
              
                while (rs.next())
                {
                    Object row[] = {
                           rs.getString("paper"),
                      rs.getString("groupp"),
                         rs.getString("pphone"),
                       rs.getString("phone"),
                       rs.getString("class"),
                        rs.getString("name"),
                        rs.getString("serial"),
                                };
                    model.addRow(row);
                    
                }
        }
        catch (SQLException ex) {
            
        }
    }
     public void clear()
 {
 phone1.setText("");
 serial1.setText("");
 name1.setText("");  
 cmgroup1.setSelectedIndex(0);


 
 }
     
     
       
        

     
}
