/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classpriv;

import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author amnassar
 */
public final class studentbook extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
       Connection con ;
    PreparedStatement pst ;
    ResultSet rs;
     public String y ;
    
   
    public studentbook() {
        initComponents();
        con=DBConnect.connect();
          auto_id();
           Groups();
           classes();
        tablelord();
        clear();
         name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
           phone.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
           pphone.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
           cmgroups.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
            TableCellRenderer rendererFromHeader = tdetails.getTableHeader().getDefaultRenderer();
JLabel headerLabel = (JLabel) rendererFromHeader;
headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tdetails.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
          
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdetails = new javax.swing.JTable();
        autoserial = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cmclass = new javax.swing.JComboBox();
        cmgroups = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        pphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        txtpaper = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialid = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdetails.setBackground(new java.awt.Color(17, 39, 37));
        tdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tdetails.setForeground(new java.awt.Color(255, 255, 255));
        tdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "قيمه الحجز", "المذكرات", "المجموعه", "رقم ولي الامر", "رقم الهاتف", "الصف", "اسم الطالب", "الرقم التسلسلي"
            }
        ));
        tdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails.setRowHeight(25);
        tdetails.setRowMargin(2);
        tdetails.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tdetails.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdetails);
        if (tdetails.getColumnModel().getColumnCount() > 0) {
            tdetails.getColumnModel().getColumn(2).setMinWidth(400);
            tdetails.getColumnModel().getColumn(2).setPreferredWidth(400);
            tdetails.getColumnModel().getColumn(2).setMaxWidth(400);
            tdetails.getColumnModel().getColumn(7).setMinWidth(100);
            tdetails.getColumnModel().getColumn(7).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 920, 280));

        autoserial.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        autoserial.setForeground(new java.awt.Color(255, 255, 255));
        autoserial.setText("لإثسف");
        jPanel10.add(autoserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 60));

        delete.setBackground(new java.awt.Color(98, 113, 146));
        delete.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("مسح");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel10.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 180, 50));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("المجموعه");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 160, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("الاسم");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 160, -1));

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 230, 30));

        cmclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "الثالث الثانوي" }));
        cmclass.setEnabled(false);
        jPanel10.add(cmclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 230, 30));

        cmgroups.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel10.add(cmgroups, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 230, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("قيمه الحجز");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 110, -1));

        amount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 90, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("المذكرات");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 100, -1));

        save.setBackground(new java.awt.Color(98, 113, 146));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("حفظ");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel10.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, 40));

        pphone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(pphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 230, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("تليفون ولي الامر");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 180, -1));

        phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 230, 30));

        txtpaper.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(txtpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("الصف");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 160, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("رقم التليفون");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 160, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/myback.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid.setText("jLabel1");
        jPanel10.add(serialid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        if(serialid.getText().trim().isEmpty())
        {

            String namee = name.getText();
            String groups = cmgroups.getSelectedItem().toString();
            String typee = cmclass.getSelectedItem().toString();
            String phonee = phone.getText();
            String pphonee = pphone.getText();
            String seriall =autoserial.getText();
           try
           {int amountt = Integer.parseInt(amount.getText());
           int paper = Integer.parseInt(txtpaper.getText());
           
           
            

            if( name.getText().trim().isEmpty() || cmgroups.getSelectedItem().toString().trim().isEmpty() || cmclass.getSelectedItem().toString().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, " من فضلك ادخل اسم الطاب و مجموعه الطالب و الصف");
            }
            else
            {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
                if(dialogResult == 0) {
                    try{
                        String sql = "INSERT INTO mrahmed.bookstudents (type,paper,name, phone, pphone,groupp,serial,amount) VALUES"
                        + " ('"+typee+"','"+paper+"','"+namee+"','"+phonee+"','"+pphonee+"','"+groups+"','"+seriall+"',"+amountt+")";
                        pst = (PreparedStatement)con.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "تم اضافه حجز الطالب بنجاح");

                        clear();
                        tablelord();
                        auto_id();

                    }
                    catch(Exception e ){
                        JOptionPane.showMessageDialog(null,e);
                    }

                }
                else
                {JOptionPane.showMessageDialog(this, " تم الغاء العمليه");

                }
            }}
           catch(Exception e)
                   {
                       JOptionPane.showMessageDialog(this, "قيمه الحجز غير صحيحه و المذكره");
                       amount.requestFocus();
                       amount.setText("");
                               }
            
        }
        else
        {
          
            
            String namee = name.getText();
            String group = cmgroups.getSelectedItem().toString();
            String typee = cmclass.getSelectedItem().toString();
            String phonee = phone.getText();
            String pphonee = pphone.getText();
            String serial = autoserial.getText();
            try{
            int amountt = Integer.parseInt(amount.getText());
            int paper = Integer.parseInt(txtpaper.getText());
             int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
                if(dialogResult == 0) {
                 try {

                    String sql = "UPDATE mrahmed.bookstudents SET type='"+typee+"',paper='"+paper+"', name='"+namee+"', groupp='"+group+"', phone='"+phonee+"',amount="+amountt+", pphone='"+pphonee+"'  WHERE serial='"+serialid.getText()+"'";
                    pst=(PreparedStatement) con.prepareStatement(sql);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "تم تعديل بيانات الطالب بنجاح");
                    clear();
                    tablelord();

                } catch (SQLException ex) {
                           JOptionPane.showMessageDialog(null,ex);
                }
            }
            else
            {JOptionPane.showMessageDialog(this, " تم الغاء العمليه");
               

            }
            }
            catch(Exception e )
            { JOptionPane.showMessageDialog(null,"قيمه الحجز و المذكره غير صحيح  ");}
           
        }
    }//GEN-LAST:event_saveActionPerformed

    private void tdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetailsMouseClicked
        DefaultTableModel tmodel =(DefaultTableModel)tdetails.getModel();
        //bid,name, price, publisher, book_type, b_code, date, category
        int selectrowindex=tdetails.getSelectedRow();
       serialid.setText(tmodel.getValueAt(selectrowindex,7).toString());
        name.setText(tmodel.getValueAt(selectrowindex, 6).toString());
        cmclass.setSelectedItem(tmodel.getValueAt(selectrowindex, 5).toString());
        phone.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        pphone.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        cmgroups.setSelectedItem(tmodel.getValueAt(selectrowindex, 2).toString());
        amount.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        txtpaper.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        
      
        
       // paper.setSelected(false);
  
    }//GEN-LAST:event_tdetailsMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if(serialid.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "من فضلك اختر الطالب المراد ازالته ");

        }
        else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
            if(dialogResult == 0) {
                try {
                    String sql = "DELETE FROM mrahmed.bookstudents WHERE serial='"+serialid.getText()+"'";
                    pst=(PreparedStatement) con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(rootPane, " تم ازاله الطالب بنجاح");
                    tablelord();
                } catch (SQLException ex) {

                }
                clear();
            }
            else
            {

                JOptionPane.showMessageDialog(this, " تم الغاء العمليه");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel autoserial;
    private javax.swing.JComboBox cmclass;
    private javax.swing.JComboBox cmgroups;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pphone;
    private javax.swing.JButton save;
    private javax.swing.JLabel serialid;
    private javax.swing.JTable tdetails;
    private javax.swing.JTextField txtpaper;
    // End of variables declaration//GEN-END:variables

   public void tablelord()
    {
        try {
            String sqll = "SELECT paper,serial,name,type,phone,pphone,groupp,amount FROM mrahmed.bookstudents";
              pst=(PreparedStatement) con.prepareStatement(sqll);
            rs=pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel)tdetails.getModel(); 
                model.setRowCount(0);
              int k = 0;
                while (rs.next())
                {
                    Object row[] = {
                        rs.getString("amount"),
                        rs.getString("paper"),
                      rs.getString("groupp"),
                         rs.getString("pphone"),
                       rs.getString("phone"),
                       rs.getString("type"),
                        rs.getString("name"),
                        rs.getString("serial"),
                                };
                    model.addRow(row);
                    k++;
                }
                 for(int i = k ;i<11;i++)
                {
                 Object rowData[] = {
                       "",
                     "",
                     "",
                     "",
                     "",
                       };
                model.addRow(rowData);
                }
        }
        catch (SQLException ex) {
            
        }
    }
     public void clear()
 {
 name.setText("");  
 phone.setText("");
 pphone.setText("");
 cmgroups.setSelectedIndex(0);
 cmclass.setSelectedIndex(0);
 serialid.setText("");
 amount.setText("");
 txtpaper.setText("");

 
 }
       public void auto_id(){

         try {
             String sql = "SELECT serial FROM mrahmed.bookstudents ORDER BY serial DESC LIMIT 1";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             if(rs.next()){
                 String rnno=rs.getString("serial");
                 int co=rnno.length();
                 String txt=rnno.substring(0,2);
                 String num = rnno.substring(2,co);
                 int n = Integer.parseInt(num);
                 n++;
                 String snum=Integer.toString(n);
                 String ftxt=txt+snum;
                 autoserial.setText(ftxt);
             }
             else
             {
                 autoserial.setText("BK1001");
             }
         } catch (SQLException ex) {
            
         }
    
}
        public void Groups()
   {
        try {
             String sql="SELECT GroupName  FROM mrahmed.groups where type = 'حجز' ";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                String name = rs.getString("GroupName");
                
                cmgroups.addItem(name);
  
             }

         } catch (SQLException ex) {
             
         }
   }
             public void classes()
   {
        try {
             String sql="SELECT classname  FROM mrahmed.class ";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                String name = rs.getString("classname");
                
                cmclass.addItem(name);
  
             }

         } catch (SQLException ex) {
             
         }
   }
     
}
